### ISSUE TITLE
Make \r\n parsing work

### ISSUE THREAD

**Issue by mohammad-aqajani** [cdown/srt#34]
after integer index I have \r\n instead of \n when convert srt to string as parse function input...
i have to modify this code!

**Comment by cdown** [comment]
If you are on Windows, this will work natively (CRLF is `\n` on Windows).

If you are not, you could convert it. It's also not that difficult to make an optional `\r` part of the parsing on any platform, I can implement that soon.

**Comment by cdown** [comment]
Oh, `\n` also means LF on Windows.

We should just support this, then.

**Comment by cdown** [comment]
(but the proper solution when reading from a file is to use universal newlines)

**Comment by cdown** [comment]
Provisional support in 07ca9513751ce1d9fdd36d6ad1793d323e82ac80

**Comment by cdown** [comment]
Merged in dac00515dcfcf2506d.
