### ISSUE TITLE
Personal access key

### ISSUE THREAD

**Issue by Dragas** [cdown/srt#39]
Shouldn't personal access key be added to Travis CI settings page? I mean you are exposing it in plain text if your repository is public.

![img](https://i.imgur.com/rfGAo6v.png)

**Comment by cdown** [comment]
I'm afraid I'm not sure what you're referring to. Where are you seeing an access key?

**Comment by Dragas** [comment]
At `.travis.yml` env?

**Comment by cdown** [comment]
I'm really still not seeing it in `.travis.yml`, I'm afraid. Can you give me a permalink to the exact line you're talking about? All I see are `TOXENV` declarations.

**Comment by Dragas** [comment]
https://github.com/cdown/srt/blob/49e45aeb267/.travis.yml

But now I see that the commit is about 2 years old and the current travis.yml doesn't look like that at all 🤦‍♂️ (considering i was linked from your blogpost at https://chrisdown.name/2015/09/27/auto-merging-successful-builds-from-travis-ci.html).

Sorry to bother

**Comment by cdown** [comment]
Oh, that Travis secure env is encrypted with their public key, so it's not usable by just anyone :-)

https://docs.travis-ci.com/user/encryption-keys/

Thanks for letting me know though
