### ISSUE TITLE
False Subtitle start time >= end time, or error reading time

### ISSUE THREAD

**Issue by padovaSR** [cdown/srt#44]
Hello,
I have noticed that in certain subtitles this is happening.
When I do this:
with open(path, 'r', encoding='utf-8') as f:
                textis = srt.parse(f.read())
                fine = list(textis)
                outf = srt.compose(fine)

Then in my debug window I get this:
Skipped subtitle at index 1066: Subtitle start time >= end time

But this is not correct. I have double-checked. That is not the case.

Here is file in question:
[Logan.Lucky.2017..zip](https://github.com/cdown/srt/files/1778007/Logan.Lucky.2017.zip)

**Comment by cdown** [comment]
I don't experience this (also, `list` doesn't do anything here). With e8f1ff43a904:

    In [1]: import srt

    In [2]: srt.__file__
    Out[2]: '/home/cdown/git/srt/srt.py'

    In [3]: with open('/home/cdown/Downloads/Logan.Lucky.2017.720p.BluRay.x264-GECKOS.HIb.srt') as f:
       ...:     subs = srt.parse(f.read())
       ...:

    In [4]: subs_composed = srt.compose(subs)

    In [5]:

What commit/version are you running? What's the output of `locale` in the environment you're running this in?

**Comment by padovaSR** [comment]
It is windows 7 cp1252 encoding,  I have installed srt vi aPIP.
I have checked again witout the list, the same is happening.

That subtitle in question is very short, 6ms only:
''1066
01:12:12,854 --> 01:12:12,900
Keselowski on the outside''

**Comment by padovaSR** [comment]
I have also tried from python shell, then it is all OK.
But when I call it from my wxPython gui interface than it reports skipped line.

Interesting.

**Comment by padovaSR** [comment]
It some kind of false alarm, it's coming from IDE,
but when program works alone, that line is still there, not skipped.

So, everything is ok.

regards

**Comment by cdown** [comment]
That sound really, really weird. I wonder if somehow `datetime.timedelta` is screwed up in the IDE. :-/

For now I'll close, but if you find out more I'm interested in hearing about it. Thanks for the report!
