### ISSUE TITLE
Keep getting "expected string or bytes-like object" error

### ISSUE THREAD

**Issue by arashmath** [cdown/srt#47]
Hi.
While using this library on both English and Farsi subtitles, I keep getting the error in the picture.
Can you help me with that? Thank you.
![11](https://user-images.githubusercontent.com/27275971/52943495-89ab9800-3382-11e9-88cb-981c72854b2d.png)

**Comment by cdown** [comment]
As the error message says, `srt.parse` takes a string, not a file object.

You need `sub = srt.parse(file.read())`

**Comment by arashmath** [comment]
> As the error message says, `srt.parse` takes a string, not a file object.
> 
> You need `sub = srt.parse(file.read())`

Thank you so much for your help.

**Comment by cdown** [comment]
No worries! 1fbe58e1ee93096068e656ae7d1631afc386f839 will also allow this in next srt release.
