### ISSUE TITLE
can you add make_legal_content(content) a silent mode?

### ISSUE THREAD

**Issue by goldengrape** [cdown/srt#49]
for ```srt.make_legal_content(content)```
Could you please make this function run in silent mode? or give a switch?
It returns everything of content.

and, remove <br /> something like this?

**Comment by cdown** [comment]
`make_legal_content` just uses the normal logging library, so you can use the normal logging APIs for that:

```
In [13]: logging.getLogger("srt").setLevel(logging.ERROR)                                                                                                                                                          

In [14]: srt.make_legal_content("test\n\n\n")                                                                                                                                                                      
Out[14]: 'test'
```

(notice, no logging output)

**Comment by cdown** [comment]
Thinking about this more, these should also be loglevel info. I've just done that here: 543a70ad71cde9f468153111dd64a387e9202780
