### ISSUE TITLE
Error parsing subtitles with (incorrect) single digit second timestamp

### ISSUE THREAD

**Issue by mdcollins05** [cdown/srt#55]
Hi,

I've run into an issue parsing out some subtitles from online sources. Unfortunately, the website is adding an incorrectly formatted timestamp to the end of each file.

Here's the lines being added (minus the content):

```
9999
00:00:0,500 --> 00:00:2,00
```

And here is the error generated:

```
Traceback (most recent call last):
  File "./parse_srt.py", line 209, in <module>
    sys.exit(main())
  File "./parse_srt.py", line 72, in main
    settingsYaml, args.srt, args.summary, args.dry_run, args.quiet, args.verbose
  File "./parse_srt.py", line 102, in parse_srt
    original_subtitles = list(srt.parse(original_subtitles))
  File "/home/mdcollins/.local/lib/python3.5/site-packages/srt.py", line 352, in parse
    start=srt_timestamp_to_timedelta(raw_start),
  File "/home/mdcollins/.local/lib/python3.5/site-packages/srt.py", line 222, in srt_timestamp_to_timedelta
    TS_LEN, len(ts), ts
ValueError: Expected timestamp length >= 12, but got 11 (value: 00:00:0,500)
```

Is it possible to handle this format?

Cheers!

**Comment by cdown** [comment]
Good timing! We actually now support this as of 3194597c172fef7f617361fdba442728b7730130, which will be part of the next release. I actually have been planning to release for a while but didn't get around to it, but today is as good of a time as any.

**Comment by cdown** [comment]
3.0.0 is now released, so I believe this is resolved. Let me know if you have any issues though :-)

**Comment by mdcollins05** [comment]
Awesome! I tried the update and it handles this case just fine.

Thanks much!
