### ISSUE TITLE
[Feature request]. Adding html color code tag to every line

### ISSUE THREAD

**Issue by michpas** [cdown/srt#61]
As a new feature, would it be possible to add an html font color tag to every line?
Certain modern hdr televisions do show bright white subs. Adding an <font color=#909090>    </font> does help to make the sub less bright.

**Comment by cdown** [comment]
That kind of abstract manipulation is what `srt process` is for :-)

**Comment by cdown** [comment]
I'm going to close this out, since `srt process` should work.
