### ISSUE TITLE
Can't make the compose() works

### ISSUE THREAD

**Issue by SamuelTell** [cdown/srt#62]
To me is impossible to make the composer method work. So I wrote this basic example anda everything works mostly fine for my needs, but the compose don't. Is There anything wrong with the way I'm using it?

```
from datetime import timedelta
import srt

td = timedelta(seconds=1)

a = srt.Subtitle(index=1, start=td, end=td, content='Word 1')
b = srt.Subtitle(index=2, start=td, end=td, content='Word 2')

c = [a, b]

print(srt.compose(c))

c = a.to_srt() + b.to_srt()

print("========")
print(c)

print("====")
d = list(srt.parse(c))
print(d)
```

**Comment by cdown** [comment]
It's filtered because it's never displayed (end <= start). If you want to just verbatim print the Subtitle objects, you need to use `reindex=False`.

**Comment by stuartjcameron** [comment]
You may want to adjust the docs as the same example is given there.
https://srt.readthedocs.io/en/latest/api.html#srt.compose

**Comment by SamuelTell** [comment]
That's part of the problem. I tried it before:

```
import srt
from datetime import timedelta

td = timedelta(seconds=1)

subs = [
    Subtitle(index=1, start=td, end=td, content='x'),
    Subtitle(index=2, start=td, end=td, content='y'),
    ]
compose(subs)
```

and find received this error:

```
Traceback (most recent call last):
  File "D:\Estudos Programação\Python\testes.py", line 7, in <module>
    Subtitle(index=1, start=td, end=td, content='x'),
NameError: name 'Subtitle' is not defined
```

So I could not find a way to make it works without initializing the object by

`a = srt.Subtitle(index=1, start=td, end=td, content='Word 1')`

So I'm not understanding what I'm doing wrong.

What is even weirder is, this code (from quickstart) works:

```
import srt
subtitle_generator = srt.parse('''\
1
00:31:37,894 --> 00:31:39,928
OK, look, I think I have a plan here.

2
00:31:39,931 --> 00:31:41,931
Using mainly spoons,

3
00:31:41,933 --> 00:31:43,435
we dig a tunnel under the city and release it into the wild.

''')

subtitles = list(subtitle_generator)
print(srt.compose(subtitles))
```

The beginning of the frist code was just to show that even though I have a list of Subtitle objects, the compose doesn't work.

But from my point of view, my new code and this are basicly the same: A string, trough srt.parse() -> trough list() -> srt.compose() being printed.

from datetime import timedelta
import srt

td = timedelta(seconds=1)

a = srt.Subtitle(index=1, start=td, end=td, content='Word 1')
b = srt.Subtitle(index=2, start=td, end=td, content='Word 2')

c = a.to_srt() + b.to_srt()

subtitle_generator = srt.parse(c)

subtitles = list(subtitle_generator)

print(srt.compose(subtitles))

**Comment by SamuelTell** [comment]
Thanks,

Passing `reindex=False` to `srt.compose` works for me. Or just filling the starts and ends with differente and crescent values.

**Comment by cdown** [comment]
> The creators of this module may want to adjust the docs as the same example is given there.

Huh! Thank you very much, these are supposed to be validated automatically by doctest, but it seems it isn't working, let me look into that...

**Comment by cdown** [comment]
Ok, so this was actually updated in the documentation already, but it looks like readthedocs didn't rebuild for some reason.

**Comment by cdown** [comment]
Looks like the webhook was failing. I just recreated the project on RTD and it seems to be ok now. Thanks for letting me know!

**Comment by orotau** [comment]
I got caught by this. Not sure the documentation has been updated
https://srt.readthedocs.io/en/latest/api.html

**Comment by cdown** [comment]
The documentation looks up to me, what are you seeing? It shows this example, which works:

```
>>> from datetime import timedelta
>>> start = timedelta(seconds=1)
>>> end = timedelta(seconds=2)
>>> subs = [
...     Subtitle(index=1, start=start, end=end, content='x'),
...     Subtitle(index=2, start=start, end=end, content='y'),
... ]
>>> compose(subs)  
'1\n00:00:01,000 --> 00:00:02,000\nx\n\n2\n00:00:01,000 --> ...'
```

**Comment by orotau** [comment]
Yep I got that to work too.
But with my work I had to do this `srt.compose(subs, reindex=False)` as per this Issue.
Thanks for the project
