### ISSUE TITLE
Niche offset merging for subtitles with same timestamps

### ISSUE THREAD

**Issue by kjfun** [cdown/srt#63]
First of all, thanks for the great program.  An issue I'm having is that tvs and some video players won't properly display dual language subtitles muxed with the srt-mux tool.  When there are two subtitles of different languages and with the same timestamps, only the second subtitle will be displayed.  If I go in and manually edit the subtitles so that there is only one timestamp, the issue goes away.  For increased compatibility and usefulness, it'd be great if there was an option in the srt-mux tool to combine subtitles with the same timestamps so that there is only one subtitle per timestamp with the content  from both languages.  Thanks.

**Comment by cdown** [comment]
Hey! That sounds... not great, but yes, it shouldn't be too hard to add that functionality. I suppose we can do it as part of the sliding window check.
