### ISSUE TITLE
WebVTT and microseconds format

### ISSUE THREAD

**Issue by Smolky** [cdown/srt#66]
Hi. First of all, thanks very much for this tool. I found it quite useful

I am trying to use it to create subtitles compatibles with WEBVTT

Some of the adaptations needed to create the WebVTT are easy for me. For example, I could attach esaly the voices in the cues prepending `<v speaker_1>` or by including the `WEBVTT` header at top of the file.

Howerver, according to this example:
https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API

Subtitles have some form of:
```
WEBVTT

00:01.000 --> 00:04.000
- Never drink liquid nitrogen.

00:05.000 --> 00:09.000
- It will perforate your stomach.
- You could die.

```
As you can notice, microseconds are displayed with dots "." rather than commas ",". However, I notice that the "comma" is hardcode in the code so it is not easy for me to change it. I suposse that I could parse the file after generated and change it by using regular expressions. 

Does it makes sense to make the timedelta format parametrizable?

**Comment by cdown** [comment]
Hey! Looking at that document, I suspect supporting VTT would entail inviting compatibility changes of unknown scope. Unless it's demonstrable that these are the only changes that will ever be needed, I'm inclined to suggest just use ffmpeg to change it:

    ffmpeg -i x.srt x.vtt

**Comment by cdown** [comment]
I'm going to close this for now on that basis, but let me know if there's anything else I can help with.

**Comment by Smolky** [comment]
No problem. I'll give it a try to ffmpeg

Kind regards and thanks for your time
