### ISSUE TITLE
[INFO] What is the purpose of 'in_place' in srt.sort_and_reindex()?

### ISSUE THREAD

**Issue by switchupcb** [cdown/srt#69]
In the process of improving my pull request for srt_tools, I couldn't understand what the purpose of the parameter 'in_place' for the sort_and_reindex() function was. If you are at my level of experience, you may benefit from this information. In short: **The _in_place_ parameter specifies whether a new subtitle will be created in memory. By default (_in_place_ = False), a new subtitle is created.**

### **srt.sort_and_reindex()**
The **function** takes an iterable (list, generators, etc) and sorts it via sorted(). The sorted() function will create a deep copy of the iterable (list) and sort it according to the **Subtitle** class _(\_\_lt\_\_, \_\_eq\_\_)._ Then we _enumerate()_ over this list (by index and by object) and yield a generator object (containing the subtitles). **Every object still refers to the same memory address.**

```python
arr = [1, 2, 3]
print('unsorted')
for i in ar:
    print(hex(id(i)))

print('\nsorted')
for i in sorted(ar):
    print(hex(id(i)))

print('\nenumerate')
for idx, i in enumerate(sorted(ar)):
    print(hex(id(i)))

print('\ngenerator')
def generator(iterable):
    for i in iterable:
        yield i

for i in generator(arr):
    print(hex(id(i)))
```

However, if 'in_place' is False (default), we will — during this process — ALSO take the **current object** and assign it to a **new Subtitle** with the same attributes. We then change the index of that **new deep copied object**.

**What is the difference in using _in\_place_?**
If _in_place_ was True, you wouldn't assign the **current object** to any other object. This means that you would **NOT** create a new object in memory **for each subtitle _in the now-sorted list._**

You can use the following code to test this _(where skip=False such that blank captions aren't removed)_:
```python
subs = list(subs) # add subs to memory (since a generator only allows us to read once)
len_subs = len(subs) # Assigning length of subs is faster over time even if len(subs) is O(1) Lookup

# sorting 'not' in place (the default value) returns every captions
diff_snip = []
sort_not_in_place = list(srt.sort_and_reindex(subs, skip=False))
for i in range(len_subs):
    subs_address = hex(id(subs[i]))
    snip_address = hex(id(sort_not_in_place[i]))

    if subs_address != snip_address:
        diff_snip.append((subs_address, snip_address))
print('Sorting not in place: ', len(diff_snip), 'differences\n', diff_snip)

# sorting in place only returns out of order captions
diff_sip = []
sort_in_place = list(srt.sort_and_reindex(subs, in_place=True, skip=False))
for i in range(len_subs):
    subs_address = hex(id(subs[i]))
    sip_address = hex(id(sort_in_place[i]))

    if subs_address != sip_address:
        diff_sip.append((subs_address, sip_address))
print('\nSorting in place:\n', len(diff_sip), 'differences\n', diff_sip)
```
The output:
![sipvsnip](https://user-images.githubusercontent.com/81384235/115310252-202a9e00-a133-11eb-9afe-3a3de06e3c63.png)

**Comment by cdown** [comment]
This looks like a statement rather than a question, so closing, but the concept of being "in-place" is described here: https://en.wikipedia.org/wiki/In-place_algorithm
