### ISSUE TITLE
[proposal] Improve SEO

### ISSUE THREAD

**Issue by switchupcb** [cdown/srt#71]
**Keyword:** 'srt github'

### 1
You should change the project description (**About**) to the API description:
> srt is a simple library for parsing, modifying, and composing SRT files.
### 2
Perhaps, figure out how to get the _**Github** account notice_ in the website description.
![image](https://user-images.githubusercontent.com/81384235/118029890-37237100-b32a-11eb-912e-ec8c19097609.png)

An _srt_ is also a car, so I wouldn't optimize for that specifically.

**Comment by cdown** [comment]
I don't have interests in SEO, people can use the library or not.

**Comment by switchupcb** [comment]
> I don't have interests in SEO, people can use the library or not. This isn't a product trying to be sold, but something to scratch my own itch that happens to be useful for other people and programs.

Sure, but it makes it easier to find on Google. Saves time if you use the search to get to the page. How are people supposed to contribute if we have trouble finding it?

**Comment by cdown** [comment]
> How are people supposed to contribute if we have trouble finding it?

That's really putting the cart before the horse: this isn't a project that needs vast swathes of volunteers. There's no expectation that people contribute.
