### ISSUE TITLE
Can you explain to me how to use linear-timeshift

### ISSUE THREAD

**Issue by OilSubjectLoss7** [cdown/srt#79]
The example and guide(?) is confusing to me

**Comment by cdown** [comment]
Ah yes, the example is quite wrong. Does c18648a4d83 help?

You can think of f1/t1 and f2/t2 as being two pins. fN is the start location of the pin, tN is the end location of the pin, and all of the other subtitles are pulled proportionally to fit.

**Comment by OilSubjectLoss7** [comment]
I think i understand it a little better now. I gotta test it out.

So it's quite similar to;

First/Beginning line start time + Last/end line start time, in most subtitle editor program
So two inputs;
 hhmmss,ms / hhmmss,ms


The only diffrence with your script, you can choose any two lines as starting point or pins as you call them and there's four inputs instead of two. And the program will calculate some stuff and the rest of lines will be adjusted properly.

I'm still having problem understanding the t1,t2 stuff.

Are f1/f2 similar to the start time inputs like in most sub editor, what about the t1/t2 stuff? Are they like the end time stamps inputs? For what purpose? For shortening or prolonging all the lines?
