### ISSUE TITLE
Update to 3.5.2 via pip exits with error

### ISSUE THREAD

**Issue by SteffenBauer** [cdown/srt#83]
When I try to upgrade srt via `pip install -U srt` from 3.5.1 to 3.5.2, pip breaks with error. Previous installations worked without problem.

Debian 10
Python 3.7.3
pip 22.0.3
setuptools 60.9.3

pip console output:

```
Collecting srt
  Downloading srt-3.5.2.tar.gz (24 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      /home/steffen/.local/lib/python3.7/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'python_requires'
        warnings.warn(msg)
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: invalid command 'egg_info'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by cdown** [comment]
Weirdly you say you have setuptools installed, but if this is the case then I don't see why distutils should be getting involved at all. Are you sure this environment has setuptools?

**Comment by cdown** [comment]
Anyway, after ef93bf0, if setuptools is missing you'll just get an ImportError if setuptools is missing for some reason. :)

**Comment by SteffenBauer** [comment]
Well, its mysterious, as setuptools is definitely installed.

I managed to update it just right now by locally building a .whl by running `python3 setup.py bdist_wheel`, and then installing the generated `srt-3.5.2-py3-none-any.whl`

**Comment by SteffenBauer** [comment]
Update on this:
I got also the same problem upgrading other packages with pip.
Downgrading setuptools to 60.8.2 solved the problem; upgrading pypi packages, including srt, then works.
Browsing the setuptools repository on github shows that currently there are a lot of bug reports regarding handling of egg.
So the problem quite definitely is not in the srt package, but something was broken in the newest setuptools.

**Comment by cdown** [comment]
Thanks for the update! That's helpful to know.

**Comment by SteffenBauer** [comment]
Next update: I submitted an issue report to setuptools, turned out that everything works in a virtual environment or docker environment.
After a lot of investigating, the reason was a corruption in my local python lib directory. Funny that this caused an issue only with the newest setuptools, but not with older ones.
After removing the corruption artifact, and a clean reinstall of setuptools, srt can now be installed again smoothly and without problem.
