### ISSUE TITLE
Request: set gap between each subtitle-lines

### ISSUE THREAD

**Issue by OilSubjectLoss7** [cdown/srt#84]
Like `srt gap -t 80 f.srt -o new.srt`
Before

> 00:57,239 01:00,056
> 01:00,056 01:04,340

After
> 00:57,239 00:59,975
> 01:00,056 01:04,340

**Comment by cdown** [comment]
Seems too specific/niche for a mainline tool. Easy enough to do with the library though, just sort the subtitles, look for overlapping start/end times, and reduce the timedelta by however much you want.
