### ISSUE TITLE
Incorrect number in teaser

### ISSUE THREAD

**Issue by abcdenis** [cdown/srt#86]
Hi,
teaser text about "150 lines" references to static text.

As for now git hub shows that there is `511 lines (421 sloc)`
https://github.com/cdown/srt/blob/develop/srt.py

Is it time to update README?

**Comment by cdown** [comment]
SLOC doesn't include docstrings, since docstrings aren't code. With [pysloc](https://github.com/cdown/dotfiles/blob/master/bin/pysloc):

    % pysloc srt.py
    202

So it's about 200.

**Comment by cdown** [comment]
Updated the number in the readme to 200.
