### ISSUE TITLE
Making a srt file from scratch and writing/saving as a file with Python

### ISSUE THREAD

**Issue by ghostlyghastly** [cdown/srt#90]
Hi, I'm trying to convert csv files to srt format but from the beginner documentation I can't figure out how to just convert a list of lists with start time / end time / text into an srt file.

I also can't figure out how to write an SRT file.

**Comment by cdown** [comment]
Please read the quickstart [here](https://srt.readthedocs.io/en/latest/quickstart.html).

For reading from lists, construct a Subtitle object as desired and then run `srt.compose`.

You can also look at how it's done in examples in the `srt_tools` directory.
