### ISSUE TITLE
Correct each timestamp

### ISSUE THREAD

**Issue by nahtan-dev** [cdown/srt#91]
Hello, is it possible to add, for instance 30 seconds, to each timestamp of a SubRip file?

For example, if I have: 
Line 1 - Start:0s, End:2s, Text:Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Line 2 - Start:4.3s, End:8s, Text:Sed non risus.
Line 3 - Start:8s, End:15.27s, Text:Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.

Then, I will have:
Line 1 - Start:30s, End:32s, Text:Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Line 2 - Start:34.3s, End:38s, Text:Sed non risus.
Line 3 - Start:38s, End:45.27s, Text:Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.

Thanks for answering!

**Comment by cdown** [comment]
Hi! Yes, this can be done with `srt fixed-timeshift`. See the `srt_tools` directory. :-)

**Comment by nahtan-dev** [comment]
Thanks!

> Hi! Yes, this can be done with `srt fixed-timeshift`. See the `srt_tools` directory. :-)
